In [1]:
import pandas as pd

In [2]:
file_path = 'Badeel_Data.csv'
df = pd.read_csv(file_path, skiprows=1)

In [3]:
print(df.head())
print(df.columns)

         Date          name          english           manufacturer  \
0  12/22/2023  جرين موكتيلز  green mocktails        شركة ميكس تيندر
1    1/1/2024       مندولين         Mandolin                كادبوري
2    1/3/2024         جوميا            Jumia  Jumia Technologies AG
3    1/3/2024          تريو              رول       بيراميدز للتجميل
4    1/3/2024         بيبسي            Pepsi                  Pepsi

                                        details         type تم مراجعته؟  \
0               شركة جرين كولا مصر و ميكس تيندر  alternative         NaN
1                           دعم الكيان الصهيوني      boycott         NaN
2  بديل لموقع امازون و نوون للتسوق عبر الانترنت  alternative         NaN
3                               منتج محلي غالبا  alternative         NaN
4                                       صهيونيه      boycott         NaN

  داعم\بديل؟ السبب او معلومات اضافية النوع
0        NaN                     NaN   NaN
1        NaN                     NaN   NaN
2        NaN                     NaN   NaN
3        NaN                     NaN   NaN
4        NaN                     NaN   NaN
Index(['Date', 'name', 'english', 'manufacturer', 'details', 'type',
       'تم مراجعته؟', 'داعم\بديل؟', 'السبب او معلومات اضافية', 'النوع'],
      dtype='object')

# Data preprocessing

In [4]:
# Remove empty columns
df = df.dropna(axis=1, how='all')

In [5]:
df.columns = ['Date', 'Name', 'English Name', 'Manufacturer', 'Details', 'Type', 'Reviewed', 'Alternate', 'Additional Info', 'Type Again']

In [6]:
df.reset_index(inplace=True)
df.rename(columns={'index': 'Original Index'}, inplace=True)

In [7]:
print("Cleaned DataFrame:")
display(df)

Cleaned DataFrame:

,Original Index,Date,Name,English Name,Manufacturer,Details,Type,Reviewed,Alternate,Additional Info,Type Again
0,0,12/22/2023,جرين موكتيلز,green mocktails,شركة ميكس تيندر,شركة جرين كولا مصر و ميكس تيندر,alternative,NaN,NaN,NaN,NaN
1,1,1/1/2024,مندولين,Mandolin,كادبوري,دعم الكيان الصهيوني,boycott,NaN,NaN,NaN,NaN
2,2,1/3/2024,جوميا,Jumia,Jumia Technologies AG,بديل لموقع امازون و نوون للتسوق عبر الانترنت,alternative,NaN,NaN,NaN,NaN
3,3,1/3/2024,تريو,رول,بيراميدز للتجميل,منتج محلي غالبا,alternative,NaN,NaN,NaN,NaN
4,4,1/3/2024,بيبسي,Pepsi,Pepsi,صهيونيه,boycott,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
441,441,45441.67979,تويست,Twist,Twist,مشروب طاقه,boycott,NaN,NaN,NaN,NaN
442,442,45442.88209,هوهوز,NaN,أيدينا نفس شركة مولتو,راجعوا يا جدعان عاملين شغل كويس كملوا المعلوما...,boycott,NaN,NaN,NaN,NaN
443,443,NaN,ياهوووه,Yahoo,Faragalla Group,مجموعة فرج الله المملوكة لفرج عامر بتصدر مواد ...,Boycott,NaN,داعم,مجموعة فرج الله المملوكة لفرج عامر بتصدر مواد ...,مشروبات
444,444,NaN,فرجلو عصير,Faragalla,Faragalla Group,مجموعة فرج الله المملوكة لفرج عامر بتصدر مواد ...,Boycott,NaN,داعم,مجموعة فرج الله المملوكة لفرج عامر بتصدر مواد ...,مواد غذائية
445,445,NaN,NaN,Faragalla,Faragalla Group,مجموعة فرج الله المملوكة لفرج عامر بتصدر مواد ...,Boycott,NaN,داعم,مجموعة فرج الله المملوكة لفرج عامر بتصدر مواد ...,مواد غذائية

### Work with the duplicated data

In [8]:
# Find duplicated name
duplicate_names = df[df.duplicated(['Name'], keep=False)]
print("Duplicate Names:")
display(duplicate_names)

Duplicate Names:

,Original Index,Date,Name,English Name,Manufacturer,Details,Type,Reviewed,Alternate,Additional Info,Type Again
29,29,1/6/2024,منفذ,Monafiz,Mobtakr LLC,منفذ منصة عربية للعمل وبيع الخدمات المصغرة.,alternative,NaN,NaN,NaN,NaN
34,34,1/7/2024,إندومي,Indomie,Indofood,الشركة المصنعة مقرها في إندونيسيا لكن في شركة ...,unsure,NaN,NaN,NaN,NaN
36,36,1/7/2024,اوكسي,Oxi,أرما للصابون والمنظفات,الشركة عربيه بمدينة العاشر من رمضان ، المنتج ب...,alternative,NaN,NaN,NaN,NaN
40,40,1/7/2024,نيفيا,Nivea,Beiersdorf Global AG,لها أصول أمريكية وألمانية,boycott,NaN,NaN,NaN,NaN
44,44,1/7/2024,اوكسي,Oxi,Henkel,تبع شركه امريكيه,boycott,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
436,436,45439.5416,تويست,Twist,Twist,,unsure,NaN,NaN,NaN,NaN
438,438,45440.46715,بيك رولز,NaN,Edita,معظم الأسهم أجنبية,boycott,NaN,NaN,NaN,NaN
439,439,45440.73341,بيك رولز,NaN,اديتا,لأنها تدعم اسرائيل,boycott,NaN,NaN,NaN,NaN
441,441,45441.67979,تويست,Twist,Twist,مشروب طاقه,boycott,NaN,NaN,NaN,NaN
442,442,45442.88209,هوهوز,NaN,أيدينا نفس شركة مولتو,راجعوا يا جدعان عاملين شغل كويس كملوا المعلوما...,boycott,NaN,NaN,NaN,NaN

In [9]:
# Sort duplicate name by Name
print("Duplicate Names Sorting by Name:")
duplicate_names.sort_values(by='Name')

Duplicate Names Sorting by Name:

,Original Index,Date,Name,English Name,Manufacturer,Details,Type,Reviewed,Alternate,Additional Info,Type Again
343,343,3/22/2024,Asan,NaN,Naturz,هل هذا المنتج يدعم الكيان او لا,boycott,NaN,NaN,NaN,NaN
342,342,3/22/2024,Asan,NaN,Asan,بديل,boycott,NaN,NaN,NaN,NaN
133,133,1/29/2024,test,test,test,testt,boycott,NaN,NaN,NaN,NaN
363,363,4/4/2024,test,test,test,testtesttest,boycott,NaN,NaN,NaN,NaN
320,320,3/13/2024,آبل,iPhone,Apple,Please check if we should boycott it or not.,unsure,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
442,442,45442.88209,هوهوز,NaN,أيدينا نفس شركة مولتو,راجعوا يا جدعان عاملين شغل كويس كملوا المعلوما...,boycott,NaN,NaN,NaN,NaN
227,227,1/31/2024,ويندوز,Windows,Microsoft,نظام تشغيل مدفوع من صنع شركة أمريكية.,boycott,NaN,NaN,NaN,NaN
106,106,1/29/2024,ويندوز,Windows,Microsoft,https://twitter.com/satyanadella/status/171197...,boycott,NaN,NaN,NaN,NaN
206,206,1/31/2024,يوني كافيه,Uni Cafe,داماس للصناعات الغذائية,https://www.damas-food.net,alternative,NaN,NaN,NaN,NaN
56,56,1/9/2024,يوني كافيه,UniCafe,داماس,بديل عن نسكافيه,alternative,NaN,NaN,NaN,NaN

In [10]:
# Export duplicates in a csv form
output_file_path = 'duplicates.csv'
duplicate_names.sort_values(by='Name').to_csv(output_file_path, index=False, encoding='utf-8-sig')

print(f"Duplicate rows have been exported to {output_file_path}")

Duplicate rows have been exported to duplicates.csv

In [11]:
def merge_details(group):
    return pd.Series({
        'Original Index': ', '.join(map(str, group['Original Index'].tolist())),
        'Date': ', '.join(group['Date'].dropna().astype(str).unique()),
        'English Name': ', '.join(group['English Name'].dropna().astype(str).unique()),
        'Manufacturer': ', '.join(group['Manufacturer'].dropna().astype(str).unique()),
        'Details': ' | '.join(group['Details'].dropna().astype(str).unique()),
        'Type': ', '.join(group['Type'].dropna().astype(str).unique()),
        'Reviewed': ', '.join(group['Reviewed'].dropna().astype(str).unique()),
        'Alternate': ', '.join(group['Alternate'].dropna().astype(str).unique()),
        'Additional Info': ' | '.join(group['Additional Info'].dropna().astype(str).unique()),
        'Type Again': ', '.join(group['Type Again'].dropna().astype(str).unique()),
    })

In [12]:
# merged_duplicates variable
merged_duplicates = duplicate_names.groupby('Name').apply(merge_details).reset_index()

In [13]:
# Export duplicates by mergeing their detail as a csv form
output_file_path = 'merged_duplicates.csv' 
merged_duplicates.to_csv(output_file_path, index=False, encoding='utf-8-sig')

print(f"Merged duplicate rows have been exported to {output_file_path}")

Merged duplicate rows have been exported to merged_duplicates.csv

In [14]:
# Remove original duplicates from the DataFrame
non_duplicates = df[~df.duplicated(['Name'], keep=False)]

# Combine the non-duplicate rows with the merged duplicate rows
final_df = pd.concat([non_duplicates, merged_duplicates], ignore_index=True)

In [15]:
# Sort by index
final_df['Original Index'] = final_df['Original Index'].apply(lambda x: int(x.split(',')[0]) if isinstance(x, str) else x)
final_df = final_df.sort_values(by='Original Index')

In [16]:
# Export Final df without duplicate as a csv form
output_file_path = 'final_merged_data.csv'
final_df.to_csv(output_file_path, index=False, encoding='utf-8-sig')

print(f"Final df with merged duplicates has been exported to {output_file_path}")

Final df with merged duplicates has been exported to final_merged_data.csv

### Filtering data by types

In [17]:
def filter_by_type(df, type_value):
    return df[df['Type'] == type_value]

In [18]:
# Filter by 'boycott' 
boycott_df = filter_by_type(df, 'boycott')
print("Filtered by 'boycott' Type:")
display(boycott_df)

# Export as a csv form
output_file_path = 'Type_boycott.csv' 
boycott_df.to_csv(output_file_path, index=False, encoding='utf-8-sig')
print(f"Feltering by Type 'boycott' have been exported to {output_file_path}")

Filtered by 'boycott' Type:

,Original Index,Date,Name,English Name,Manufacturer,Details,Type,Reviewed,Alternate,Additional Info,Type Again
1,1,1/1/2024,مندولين,Mandolin,كادبوري,دعم الكيان الصهيوني,boycott,NaN,NaN,NaN,NaN
4,4,1/3/2024,بيبسي,Pepsi,Pepsi,صهيونيه,boycott,NaN,NaN,NaN,NaN
6,6,1/3/2024,نون دوت كوم,Noon,محمد العبار,دعم اسرائيل ماديا,boycott,NaN,NaN,NaN,NaN
16,16,1/4/2024,دييل,Deel,Deel inc,Israeli founder,boycott,NaN,NaN,NaN,NaN
21,21,1/4/2024,جود فرانس,good france,Soreal,دورت كثير و لقيت علي ابلكيشن اسمه Sa7wa انه د...,boycott,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
437,437,45439.82101,Degree,Degree Clinical protection,Unilever,الشركه الام المفروض مقاطعه لكن ده المنتج الطبي...,boycott,NaN,NaN,NaN,NaN
438,438,45440.46715,بيك رولز,NaN,Edita,معظم الأسهم أجنبية,boycott,NaN,NaN,NaN,NaN
439,439,45440.73341,بيك رولز,NaN,اديتا,لأنها تدعم اسرائيل,boycott,NaN,NaN,NaN,NaN
441,441,45441.67979,تويست,Twist,Twist,مشروب طاقه,boycott,NaN,NaN,NaN,NaN
442,442,45442.88209,هوهوز,NaN,أيدينا نفس شركة مولتو,راجعوا يا جدعان عاملين شغل كويس كملوا المعلوما...,boycott,NaN,NaN,NaN,NaN

Feltering by Type 'boycott' have been exported to Type_boycott.csv

In [19]:
# Filter by 'alternative' 
alternative_df = filter_by_type(df, 'alternative')
print("Filtered by 'alternative' Type:")
display(alternative_df)

# Export as a csv form
output_file_path = 'Type_alternative.csv' 
alternative_df.to_csv(output_file_path, index=False, encoding='utf-8-sig')
print(f"Feltering by Type 'alternative' have been exported to {output_file_path}")

Filtered by 'alternative' Type:

,Original Index,Date,Name,English Name,Manufacturer,Details,Type,Reviewed,Alternate,Additional Info,Type Again
0,0,12/22/2023,جرين موكتيلز,green mocktails,شركة ميكس تيندر,شركة جرين كولا مصر و ميكس تيندر,alternative,NaN,NaN,NaN,NaN
2,2,1/3/2024,جوميا,Jumia,Jumia Technologies AG,بديل لموقع امازون و نوون للتسوق عبر الانترنت,alternative,NaN,NaN,NaN,NaN
3,3,1/3/2024,تريو,رول,بيراميدز للتجميل,منتج محلي غالبا,alternative,NaN,NaN,NaN,NaN
7,7,1/4/2024,يوجو,Ugo,Management gate,منتج بديل لبيبسي وكوكا كولا,alternative,NaN,NaN,NaN,NaN
8,8,1/4/2024,باريستاز,Baristas,شاب اسمه محمد,شاب اسمه محمد بيعمل بديل النسكافيه,alternative,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
416,416,5/5/2024,آيس كوفى - هيلثى,Ice-Coffe Healthy,Healthy,هذا المنتج غير داعم .,alternative,NaN,NaN,NaN,NaN
421,421,5/14/2024,سيناي,cynay.com,Mohamed ALM,محرك بحث مصري داعم للقضية الفلسطينية \r\ncynay...,alternative,NaN,NaN,NaN,NaN
424,424,5/16/2024,أوه,Eau,شركة النور للصناعة,زجاجة ماء,alternative,NaN,NaN,NaN,NaN
429,429,45431.8165,بلند,blend,Blend coffee factory,شركة مصرية بتعمل قهوة اسبريسو و نسكافيه و فلتر...,alternative,NaN,NaN,NaN,NaN
430,430,45431.81973,سيلاز,Seelaz,Seelaz,شركة مصرية بتعمل بن تركي و قهوة اسبريسو و نسكا...,alternative,NaN,NaN,NaN,NaN

Feltering by Type 'alternative' have been exported to Type_alternative.csv

In [20]:
# Filter by 'unsure' 
unsure_df = filter_by_type(df, 'unsure')
print("Filtered by 'unsure' Type:")
display(unsure_df)

# Export as a csv form
output_file_path = 'Type_unsure.csv' 
unsure_df.to_csv(output_file_path, index=False, encoding='utf-8-sig')
print(f"Feltering by Type 'unsure' have been exported to {output_file_path}")

Filtered by 'unsure' Type:

,Original Index,Date,Name,English Name,Manufacturer,Details,Type,Reviewed,Alternate,Additional Info,Type Again
5,5,1/3/2024,جرين كولا,Green Cola,Green Cola Hellas,منتج يوناني وغالباً داعم من بحث سريع علي جوجل ...,unsure,NaN,NaN,NaN,NaN
10,10,1/4/2024,أونو,UNO,Orouba coffee company,هو المفروض مش مقاطعة بس انا اول مرة اسمع عن ال...,unsure,NaN,NaN,NaN,NaN
11,11,1/4/2024,مشروب فولت,volt energy drink,volt.eg,مش عارف اي تفاصيل😁,unsure,NaN,NaN,NaN,NaN
14,14,1/4/2024,تيم كولا برتقال ليمون صودا,Pepsi,Pepsi,مكتوب علي العبوة بيبسي بقشان..,unsure,NaN,NaN,NaN,NaN
15,15,1/4/2024,لولو ماركت,Lulu Market,LuLu Group International,\nلولو هي شركة اماراتيه هندية الاصل \nhttps://...,unsure,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
433,433,45434.02187,أقوابيورتى,Aquapurity,رتش لاند,مياه غازية,unsure,NaN,NaN,NaN,NaN
434,434,45434.02287,أقوا دلتا,Aqua delta,Wapco,مياه غازية,unsure,NaN,NaN,NaN,NaN
435,435,45436.49578,ديتول,Dettol,Reckitt Benckiser,علامة تجارية لمستلزمات التنظيف والمطهرات والمع...,unsure,NaN,NaN,NaN,NaN
436,436,45439.5416,تويست,Twist,Twist,,unsure,NaN,NaN,NaN,NaN
440,440,45441.55518,عصير بيتى,Beyti,بيتى,هو عربى تقريبا بس عاوزة اتاكد ولكن معرفش تفاصيل,unsure,NaN,NaN,NaN,NaN

Feltering by Type 'unsure' have been exported to Type_unsure.csv